#!/usr/bin/env python3
"""
Amazon ML Hackathon: Business Entity Resolution Challenge
Stage 5 — Pairwise Feature Engineering Module

Extracts discriminative pairwise features between a Source 1 query entity
and a target candidate entity (Source 2 or Source 3).

Key Design Principles:
1. Strict Identity Protection: Entity IDs are NEVER used as predictive features.
2. Safety with Missing Data: Empty or missing addresses are safely flagged and
   never generate false positive string similarity signals.
3. Multilingual & Multi-script Support: Token set/sort and character metrics
   operate on normalized Unicode text (NFKC, accent-normalized, Devanagari preserved).
4. Provenance Integration: Incorporates candidate-generation blocking passes
   and priority scores.
5. High Performance: Built on RapidFuzz C++ bindings for high-throughput feature extraction.
"""

import sys
sys.stdout.reconfigure(encoding="utf-8")

from typing import Dict, List, Optional, Tuple, Any, Sequence
import numpy as np

try:
    from rapidfuzz import fuzz, distance
    HAS_RAPIDFUZZ = True
except ImportError:
    HAS_RAPIDFUZZ = False

# Ordered list of all pairwise feature names
FEATURE_NAMES: List[str] = [
    # --- Name String Similarities ---
    "name_exact_norm",            # Binary: Exact match on normalized names
    "name_exact_cons",            # Binary: Exact match on conservative names
    "name_fuzz_ratio",            # Character Levenshtein ratio [0, 1] on normalized names
    "name_fuzz_partial_ratio",    # Substring partial match ratio [0, 1]
    "name_token_sort_ratio",      # Token sort ratio [0, 1] (word order invariant)
    "name_token_set_ratio",       # Token set ratio [0, 1] (subset/superset robust)
    "name_jaro_winkler",          # Jaro-Winkler similarity [0, 1]
    "name_len_diff",              # Absolute difference in character lengths
    "name_len_ratio",             # Min length / max length [0, 1]
    "name_shared_tokens_count",   # Count of common name tokens
    "name_token_jaccard",         # Jaccard similarity of name token sets
    "name_sorted_token_equal",    # Binary: Sorted token sequences match exactly
    "name_prefix_equal_4",        # Binary: First 4 characters match exactly
    "name_prefix_equal_6",        # Binary: First 6 characters match exactly

    # --- Corporate Suffix Features ---
    "suffix_both_present",        # Binary: Both records have corporate legal suffix
    "suffix_exact_match",         # Binary: Both have suffix and they match exactly
    "suffix_mismatch",            # Binary: Both have suffix and they differ (e.g. LLC vs Inc)
    "suffix_either_missing",      # Binary: At least one record lacks a legal suffix

    # --- Address String Similarities ---
    "addr_exact_norm",            # Binary: Exact match on normalized addresses (0 if empty)
    "addr_exact_cons",            # Binary: Exact match on conservative addresses (0 if empty)
    "addr_fuzz_ratio",            # Character Levenshtein ratio [0, 1] (0 if empty)
    "addr_token_sort_ratio",      # Address token sort ratio [0, 1] (0 if empty)
    "addr_token_set_ratio",       # Address token set ratio [0, 1] (0 if empty)
    "addr_token_jaccard",         # Address token Jaccard similarity [0, 1] (0 if empty)
    "addr_shared_tokens_count",   # Count of shared address tokens (0 if empty)
    "addr_numeric_shared_count",  # Count of shared numeric tokens (e.g. '314', '729')
    "addr_numeric_jaccard",       # Jaccard similarity of numeric tokens (house/plot numbers)
    "addr_len_diff",              # Absolute character length difference (0 if empty)
    "addr_s1_empty",              # Binary: Source 1 address is empty/missing
    "addr_cand_empty",            # Binary: Candidate address is empty/missing
    "addr_either_empty",          # Binary: Either address is empty/missing
    "addr_both_empty",            # Binary: Both addresses are empty/missing

    # --- Cross-Field & Geographic Evidence ---
    "country_match",              # Binary: Country match (1.0 for valid intra-country candidates)
    "name_addr_high_agreement",   # Binary: High name (>= 0.8) AND high addr (>= 0.8) similarity
    "name_match_addr_conflict",   # Binary: High name (>= 0.9) but low addr (< 0.15) non-empty
    "name_token_set_x_addr_jaccard", # Interaction: name_token_set_ratio * addr_token_jaccard

    # --- Candidate Generation Provenance & Priority ---
    "prov_exact_name",            # Binary: Generated by Pass 1 (Exact normalized name)
    "prov_exact_conservative",    # Binary: Generated by Pass 2 (Exact conservative name)
    "prov_sorted_name",           # Binary: Generated by Pass 3 (Sorted name tokens)
    "prov_name_bigram",           # Binary: Generated by Pass 4 (Name token bigrams)
    "prov_name_token",            # Binary: Generated by Pass 5 (Distinctive name tokens)
    "prov_addr_token",            # Binary: Generated by Pass 6 (Distinctive address tokens)
    "prov_prefix_6gram",          # Binary: Generated by Pass 7 (Character prefix 6-gram)
    "prov_num_passes",            # Integer: Number of blocking passes that triggered this pair
    "prov_blocking_score",        # Continuous: Normalized candidate generator score
]


def _calc_jaccard(set_a: set, set_b: set) -> float:
    """Computes Jaccard similarity between two sets safely."""
    if not set_a or not set_b:
        return 0.0
    intersection = len(set_a.intersection(set_b))
    union = len(set_a.union(set_b))
    return float(intersection) / float(union) if union > 0 else 0.0


def extract_pairwise_features(
    s1_rec: Dict[str, Any],
    cand_rec: Dict[str, Any],
    cand_metadata: Optional[Dict[str, Any]] = None,
) -> Dict[str, float]:
    """
    Extracts all pairwise features between a Source 1 query entity and
    a candidate entity from Source 2 or Source 3.

    Args:
        s1_rec: Preprocessed Source 1 record (dict from preprocess_record).
        cand_rec: Preprocessed target candidate record (dict from preprocess_record).
        cand_metadata: Optional candidate generation metadata (dict containing
                       'blocking_methods', 'score', etc.).

    Returns:
        Dict mapping feature name (from FEATURE_NAMES) to float value.
    """
    features: Dict[str, float] = {}

    # --------------------------------------------------------------------------
    # 1. Name Features
    # --------------------------------------------------------------------------
    s1_n_norm = s1_rec.get("name_normalized", "")
    cand_n_norm = cand_rec.get("name_normalized", "")
    s1_n_cons = s1_rec.get("name_conservative", "")
    cand_n_cons = cand_rec.get("name_conservative", "")

    s1_n_toks = s1_rec.get("name_tokens", [])
    cand_n_toks = cand_rec.get("name_tokens", [])
    s1_n_set = set(s1_n_toks)
    cand_n_set = set(cand_n_toks)

    # Exact matches
    features["name_exact_norm"] = 1.0 if s1_n_norm and (s1_n_norm == cand_n_norm) else 0.0
    features["name_exact_cons"] = 1.0 if s1_n_cons and (s1_n_cons == cand_n_cons) else 0.0

    # RapidFuzz string similarities
    if HAS_RAPIDFUZZ and s1_n_norm and cand_n_norm:
        features["name_fuzz_ratio"] = fuzz.ratio(s1_n_norm, cand_n_norm) / 100.0
        features["name_fuzz_partial_ratio"] = fuzz.partial_ratio(s1_n_norm, cand_n_norm) / 100.0
        features["name_token_sort_ratio"] = fuzz.token_sort_ratio(s1_n_norm, cand_n_norm) / 100.0
        features["name_token_set_ratio"] = fuzz.token_set_ratio(s1_n_norm, cand_n_norm) / 100.0
        features["name_jaro_winkler"] = float(distance.JaroWinkler.similarity(s1_n_norm, cand_n_norm))
    else:
        # Fallback if rapidfuzz missing or strings empty
        features["name_fuzz_ratio"] = features["name_exact_norm"]
        features["name_fuzz_partial_ratio"] = features["name_exact_norm"]
        features["name_token_sort_ratio"] = features["name_exact_norm"]
        features["name_token_set_ratio"] = features["name_exact_norm"]
        features["name_jaro_winkler"] = features["name_exact_norm"]

    # Length features
    l1, l2 = len(s1_n_norm), len(cand_n_norm)
    features["name_len_diff"] = float(abs(l1 - l2))
    features["name_len_ratio"] = (min(l1, l2) / max(l1, l2)) if max(l1, l2) > 0 else 1.0

    # Token overlap features
    shared_n_toks = s1_n_set.intersection(cand_n_set)
    features["name_shared_tokens_count"] = float(len(shared_n_toks))
    features["name_token_jaccard"] = _calc_jaccard(s1_n_set, cand_n_set)

    # Sorted token equality (e.g. 'Kumar Rajesh' vs 'Rajesh Kumar')
    features["name_sorted_token_equal"] = (
        1.0 if (s1_n_toks and cand_n_toks and sorted(s1_n_toks) == sorted(cand_n_toks)) else 0.0
    )

    # Prefix equality
    s1_compact = s1_n_norm.replace(" ", "")
    cand_compact = cand_n_norm.replace(" ", "")
    features["name_prefix_equal_4"] = (
        1.0 if (len(s1_compact) >= 4 and len(cand_compact) >= 4 and s1_compact[:4] == cand_compact[:4]) else 0.0
    )
    features["name_prefix_equal_6"] = (
        1.0 if (len(s1_compact) >= 6 and len(cand_compact) >= 6 and s1_compact[:6] == cand_compact[:6]) else 0.0
    )

    # --------------------------------------------------------------------------
    # 2. Corporate Legal Suffix Features
    # --------------------------------------------------------------------------
    s1_sfx = s1_rec.get("name_corporate_suffix")
    cand_sfx = cand_rec.get("name_corporate_suffix")
    has_s1_sfx = bool(s1_sfx and str(s1_sfx).strip())
    has_cand_sfx = bool(cand_sfx and str(cand_sfx).strip())

    features["suffix_both_present"] = 1.0 if (has_s1_sfx and has_cand_sfx) else 0.0
    features["suffix_exact_match"] = 1.0 if (has_s1_sfx and has_cand_sfx and str(s1_sfx).strip() == str(cand_sfx).strip()) else 0.0
    features["suffix_mismatch"] = 1.0 if (has_s1_sfx and has_cand_sfx and str(s1_sfx).strip() != str(cand_sfx).strip()) else 0.0
    features["suffix_either_missing"] = 1.0 if (not has_s1_sfx or not has_cand_sfx) else 0.0

    # --------------------------------------------------------------------------
    # 3. Address Features (Safely handling empty / missing addresses)
    # --------------------------------------------------------------------------
    s1_addr_empty = s1_rec.get("addr_is_empty", False) or not s1_rec.get("addr_normalized")
    cand_addr_empty = cand_rec.get("addr_is_empty", False) or not cand_rec.get("addr_normalized")

    features["addr_s1_empty"] = 1.0 if s1_addr_empty else 0.0
    features["addr_cand_empty"] = 1.0 if cand_addr_empty else 0.0
    features["addr_either_empty"] = 1.0 if (s1_addr_empty or cand_addr_empty) else 0.0
    features["addr_both_empty"] = 1.0 if (s1_addr_empty and cand_addr_empty) else 0.0

    if not s1_addr_empty and not cand_addr_empty:
        s1_a_norm = s1_rec.get("addr_normalized", "")
        cand_a_norm = cand_rec.get("addr_normalized", "")
        s1_a_cons = s1_rec.get("addr_conservative", "")
        cand_a_cons = cand_rec.get("addr_conservative", "")

        s1_a_toks = s1_rec.get("addr_tokens", [])
        cand_a_toks = cand_rec.get("addr_tokens", [])
        s1_a_set = set(s1_a_toks)
        cand_a_set = set(cand_a_toks)

        features["addr_exact_norm"] = 1.0 if (s1_a_norm and s1_a_norm == cand_a_norm) else 0.0
        features["addr_exact_cons"] = 1.0 if (s1_a_cons and s1_a_cons == cand_a_cons) else 0.0

        if HAS_RAPIDFUZZ and s1_a_norm and cand_a_norm:
            features["addr_fuzz_ratio"] = fuzz.ratio(s1_a_norm, cand_a_norm) / 100.0
            features["addr_token_sort_ratio"] = fuzz.token_sort_ratio(s1_a_norm, cand_a_norm) / 100.0
            features["addr_token_set_ratio"] = fuzz.token_set_ratio(s1_a_norm, cand_a_norm) / 100.0
        else:
            features["addr_fuzz_ratio"] = features["addr_exact_norm"]
            features["addr_token_sort_ratio"] = features["addr_exact_norm"]
            features["addr_token_set_ratio"] = features["addr_exact_norm"]

        features["addr_token_jaccard"] = _calc_jaccard(s1_a_set, cand_a_set)
        features["addr_shared_tokens_count"] = float(len(s1_a_set.intersection(cand_a_set)))

        # Numeric token overlap (plot / street numbers: '314', '729', '11')
        s1_nums = {t for t in s1_a_toks if t.isdigit()}
        cand_nums = {t for t in cand_a_toks if t.isdigit()}
        shared_nums = s1_nums.intersection(cand_nums)
        features["addr_numeric_shared_count"] = float(len(shared_nums))
        features["addr_numeric_jaccard"] = _calc_jaccard(s1_nums, cand_nums)

        features["addr_len_diff"] = float(abs(len(s1_a_norm) - len(cand_a_norm)))
    else:
        # Address is missing for at least one entity: neutral zero values
        features["addr_exact_norm"] = 0.0
        features["addr_exact_cons"] = 0.0
        features["addr_fuzz_ratio"] = 0.0
        features["addr_token_sort_ratio"] = 0.0
        features["addr_token_set_ratio"] = 0.0
        features["addr_token_jaccard"] = 0.0
        features["addr_shared_tokens_count"] = 0.0
        features["addr_numeric_shared_count"] = 0.0
        features["addr_numeric_jaccard"] = 0.0
        features["addr_len_diff"] = 0.0

    # --------------------------------------------------------------------------
    # 4. Cross-Field & Geographic Evidence Agreement
    # --------------------------------------------------------------------------
    s1_country = s1_rec.get("country", "")
    cand_country = cand_rec.get("country", "")
    features["country_match"] = 1.0 if (s1_country and s1_country == cand_country) else 0.0

    # High agreement across both name and address
    name_high = features["name_token_set_ratio"] >= 0.80
    addr_high = features["addr_token_set_ratio"] >= 0.80 and not features["addr_either_empty"]
    features["name_addr_high_agreement"] = 1.0 if (name_high and addr_high) else 0.0

    # Name matches strongly, but non-empty address has zero/very low overlap
    addr_conflict = features["addr_token_jaccard"] < 0.15 and not features["addr_either_empty"]
    name_strong = features["name_token_set_ratio"] >= 0.90
    features["name_match_addr_conflict"] = 1.0 if (name_strong and addr_conflict) else 0.0

    # Multiplicative interaction
    features["name_token_set_x_addr_jaccard"] = features["name_token_set_ratio"] * features["addr_token_jaccard"]

    # --------------------------------------------------------------------------
    # 5. Candidate Generation Provenance & Blocking Scores
    # --------------------------------------------------------------------------
    if cand_metadata:
        methods = set(cand_metadata.get("blocking_methods", []))
        score = cand_metadata.get("score", 0)

        features["prov_exact_name"] = 1.0 if "exact_name" in methods else 0.0
        features["prov_exact_conservative"] = 1.0 if "exact_conservative" in methods else 0.0
        features["prov_sorted_name"] = 1.0 if "sorted_name" in methods else 0.0
        features["prov_name_bigram"] = 1.0 if "name_bigram" in methods else 0.0
        features["prov_name_token"] = 1.0 if "name_token" in methods else 0.0
        features["prov_addr_token"] = 1.0 if "addr_token" in methods else 0.0
        features["prov_prefix_6gram"] = 1.0 if "prefix_6gram" in methods else 0.0
        features["prov_num_passes"] = float(len(methods))
        # Normalize score (standard candidate generator scores range ~8 to ~250)
        features["prov_blocking_score"] = min(1.0, float(score) / 150.0)
    else:
        # Default provenance features when metadata is absent
        features["prov_exact_name"] = features["name_exact_norm"]
        features["prov_exact_conservative"] = features["name_exact_cons"]
        features["prov_sorted_name"] = features["name_sorted_token_equal"]
        features["prov_name_bigram"] = 0.0
        features["prov_name_token"] = 1.0 if features["name_shared_tokens_count"] >= 1 else 0.0
        features["prov_addr_token"] = 1.0 if features["addr_shared_tokens_count"] >= 1 else 0.0
        features["prov_prefix_6gram"] = features["name_prefix_equal_6"]
        features["prov_num_passes"] = (
            features["prov_exact_name"] + features["prov_sorted_name"] +
            features["prov_name_token"] + features["prov_addr_token"] + features["prov_prefix_6gram"]
        )
        features["prov_blocking_score"] = features["name_fuzz_ratio"]

    return features


def extract_feature_vector(
    s1_rec: Dict[str, Any],
    cand_rec: Dict[str, Any],
    cand_metadata: Optional[Dict[str, Any]] = None,
) -> List[float]:
    """
    Extracts ordered feature vector matching FEATURE_NAMES.
    Fast path for building numpy feature arrays directly.
    """
    feat_dict = extract_pairwise_features(s1_rec, cand_rec, cand_metadata)
    return [feat_dict[fn] for fn in FEATURE_NAMES]
